source "https://rubygems.org"

ruby "3.3.1"

gem "rails", "~> 7.1.3"
gem "pg", "1.5.6"
gem "puma", ">= 6.4"
gem "queue", path: "vendor/queue"
gem "widget", github: "company/widget"
gem "no-version"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
end

group :development do
  gem "rubocop", require: false
end

if ENV["EXTRA"]
  gem "conditional", "1.0.0"
end
